import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const badges = [
  // Milestone badges
  {
    name: 'First Steps',
    description: 'Complete your first challenge',
    icon: '🌟',
    category: 'milestone',
    requirement: JSON.stringify({ type: 'challenges_completed', count: 1 }),
    xpBonus: 10,
  },
  {
    name: 'Getting Started',
    description: 'Complete 5 challenges',
    icon: '🎯',
    category: 'milestone',
    requirement: JSON.stringify({ type: 'challenges_completed', count: 5 }),
    xpBonus: 25,
  },
  {
    name: 'Math Explorer',
    description: 'Complete 25 challenges',
    icon: '🧭',
    category: 'milestone',
    requirement: JSON.stringify({ type: 'challenges_completed', count: 25 }),
    xpBonus: 50,
  },
  {
    name: 'Math Champion',
    description: 'Complete 100 challenges',
    icon: '🏆',
    category: 'milestone',
    requirement: JSON.stringify({ type: 'challenges_completed', count: 100 }),
    xpBonus: 100,
  },
  // Streak badges
  {
    name: 'On Fire',
    description: 'Maintain a 3-day streak',
    icon: '🔥',
    category: 'streak',
    requirement: JSON.stringify({ type: 'streak', count: 3 }),
    xpBonus: 15,
  },
  {
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '⚔️',
    category: 'streak',
    requirement: JSON.stringify({ type: 'streak', count: 7 }),
    xpBonus: 35,
  },
  {
    name: 'Consistency King',
    description: 'Maintain a 30-day streak',
    icon: '👑',
    category: 'streak',
    requirement: JSON.stringify({ type: 'streak', count: 30 }),
    xpBonus: 150,
  },
  // Accuracy badges
  {
    name: 'Sharp Mind',
    description: 'Get 10 correct answers in a row',
    icon: '🧠',
    category: 'accuracy',
    requirement: JSON.stringify({ type: 'correct_streak', count: 10 }),
    xpBonus: 30,
  },
  {
    name: 'Perfect Week',
    description: 'Get all answers correct for 7 days',
    icon: '💎',
    category: 'accuracy',
    requirement: JSON.stringify({ type: 'perfect_days', count: 7 }),
    xpBonus: 75,
  },
  // Speed badges
  {
    name: 'Quick Thinker',
    description: 'Solve a challenge in under 10 seconds',
    icon: '⚡',
    category: 'speed',
    requirement: JSON.stringify({ type: 'speed', seconds: 10 }),
    xpBonus: 20,
  },
  {
    name: 'Lightning Fast',
    description: 'Solve 5 challenges in under 10 seconds each',
    icon: '🚀',
    category: 'speed',
    requirement: JSON.stringify({ type: 'speed_streak', count: 5, seconds: 10 }),
    xpBonus: 50,
  },
  // Level badges
  {
    name: 'Level 5',
    description: 'Reach level 5',
    icon: '⭐',
    category: 'milestone',
    requirement: JSON.stringify({ type: 'level', count: 5 }),
    xpBonus: 25,
  },
  {
    name: 'Level 10',
    description: 'Reach level 10',
    icon: '🌟',
    category: 'milestone',
    requirement: JSON.stringify({ type: 'level', count: 10 }),
    xpBonus: 50,
  },
  // New badges to make 18 total
  {
    name: 'Early Bird',
    description: 'Complete a challenge before 8 AM',
    icon: '🐦',
    category: 'time',
    requirement: JSON.stringify({ type: 'early_bird', hour: 8 }),
    xpBonus: 15,
  },
  {
    name: 'Night Owl',
    description: 'Complete a challenge after 8 PM',
    icon: '🦉',
    category: 'time',
    requirement: JSON.stringify({ type: 'night_owl', hour: 20 }),
    xpBonus: 15,
  },
  {
    name: 'Math Master',
    description: 'Complete 500 challenges',
    icon: '🎓',
    category: 'milestone',
    requirement: JSON.stringify({ type: 'challenges_completed', count: 500 }),
    xpBonus: 200,
  },
  {
    name: 'Super Streak',
    description: 'Maintain a 60-day streak',
    icon: '💪',
    category: 'streak',
    requirement: JSON.stringify({ type: 'streak', count: 60 }),
    xpBonus: 300,
  },
  {
    name: 'Legend',
    description: 'Reach level 20 and complete 1000 challenges',
    icon: '🌈',
    category: 'milestone',
    requirement: JSON.stringify({ type: 'legend', level: 20, challenges: 1000 }),
    xpBonus: 500,
  },
]

// Local questions from Cambridge Primary Mathematics Workbook 2
const localQuestions = [
  // Unit 1 - Numbers to 100
  {
    unit: 1,
    exercise: '1.1',
    questionNum: 1,
    questionEn: 'What is 23 + 15?',
    questionVi: '23 + 15 = ?',
    answerEn: '38',
    answerVi: '38',
    type: 'calculation',
    difficulty: 1,
    hintEn: 'Add the ones first, then add the tens',
    hintVi: 'Cộng hàng đơn vị trước, sau đó cộng hàng chục',
    explanationEn: '23 + 15 = 38. (20 + 10 = 30, 3 + 5 = 8, 30 + 8 = 38)',
    explanationVi: '23 + 15 = 38. (20 + 10 = 30, 3 + 5 = 8, 30 + 8 = 38)',
    xpReward: 10,
  },
  {
    unit: 1,
    exercise: '1.1',
    questionNum: 2,
    questionEn: 'What is 45 + 32?',
    questionVi: '45 + 32 = ?',
    answerEn: '77',
    answerVi: '77',
    type: 'calculation',
    difficulty: 1,
    hintEn: 'Add the ones: 5 + 2, then add the tens: 40 + 30',
    hintVi: 'Cộng hàng đơn vị: 5 + 2, sau đó cộng hàng chục: 40 + 30',
    explanationEn: '45 + 32 = 77',
    explanationVi: '45 + 32 = 77',
    xpReward: 10,
  },
  {
    unit: 1,
    exercise: '1.2',
    questionNum: 1,
    questionEn: 'What is 67 - 24?',
    questionVi: '67 - 24 = ?',
    answerEn: '43',
    answerVi: '43',
    type: 'calculation',
    difficulty: 1,
    hintEn: 'Subtract the ones first, then the tens',
    hintVi: 'Trừ hàng đơn vị trước, sau đó trừ hàng chục',
    explanationEn: '67 - 24 = 43. (60 - 20 = 40, 7 - 4 = 3, 40 + 3 = 43)',
    explanationVi: '67 - 24 = 43',
    xpReward: 10,
  },
  {
    unit: 1,
    exercise: '1.2',
    questionNum: 2,
    questionEn: 'What is 89 - 45?',
    questionVi: '89 - 45 = ?',
    answerEn: '44',
    answerVi: '44',
    type: 'calculation',
    difficulty: 1,
    hintEn: '80 - 40 = 40, 9 - 5 = 4',
    hintVi: '80 - 40 = 40, 9 - 5 = 4',
    explanationEn: '89 - 45 = 44',
    explanationVi: '89 - 45 = 44',
    xpReward: 10,
  },
  // Unit 2 - More addition and subtraction
  {
    unit: 2,
    exercise: '2.1',
    questionNum: 1,
    questionEn: 'What is 56 + 28?',
    questionVi: '56 + 28 = ?',
    answerEn: '84',
    answerVi: '84',
    type: 'calculation',
    difficulty: 2,
    hintEn: '6 + 8 = 14, carry the 1 to the tens',
    hintVi: '6 + 8 = 14, nhớ 1 sang hàng chục',
    explanationEn: '56 + 28 = 84. When 6 + 8 = 14, we write 4 and carry 1.',
    explanationVi: '56 + 28 = 84. Khi 6 + 8 = 14, ta viết 4 và nhớ 1.',
    xpReward: 12,
  },
  {
    unit: 2,
    exercise: '2.1',
    questionNum: 2,
    questionEn: 'What is 37 + 45?',
    questionVi: '37 + 45 = ?',
    answerEn: '82',
    answerVi: '82',
    type: 'calculation',
    difficulty: 2,
    hintEn: '7 + 5 = 12, carry the 1',
    hintVi: '7 + 5 = 12, nhớ 1',
    explanationEn: '37 + 45 = 82',
    explanationVi: '37 + 45 = 82',
    xpReward: 12,
  },
  {
    unit: 2,
    exercise: '2.2',
    questionNum: 1,
    questionEn: 'What is 72 - 38?',
    questionVi: '72 - 38 = ?',
    answerEn: '34',
    answerVi: '34',
    type: 'calculation',
    difficulty: 2,
    hintEn: 'You need to borrow from the tens because 2 < 8',
    hintVi: 'Bạn cần mượn từ hàng chục vì 2 < 8',
    explanationEn: '72 - 38 = 34. Borrow 1 ten to make 12 - 8 = 4.',
    explanationVi: '72 - 38 = 34. Mượn 1 chục để có 12 - 8 = 4.',
    xpReward: 12,
  },
  // Unit 3 - Counting patterns
  {
    unit: 3,
    exercise: '3.1',
    questionNum: 1,
    questionEn: 'What comes next: 5, 10, 15, 20, ?',
    questionVi: 'Số tiếp theo là gì: 5, 10, 15, 20, ?',
    answerEn: '25',
    answerVi: '25',
    type: 'pattern',
    difficulty: 1,
    hintEn: 'Count by 5s',
    hintVi: 'Đếm theo bội số của 5',
    explanationEn: 'The pattern adds 5 each time. 20 + 5 = 25',
    explanationVi: 'Quy luật là cộng thêm 5. 20 + 5 = 25',
    xpReward: 10,
  },
  {
    unit: 3,
    exercise: '3.1',
    questionNum: 2,
    questionEn: 'What comes next: 2, 4, 6, 8, ?',
    questionVi: 'Số tiếp theo là gì: 2, 4, 6, 8, ?',
    answerEn: '10',
    answerVi: '10',
    type: 'pattern',
    difficulty: 1,
    hintEn: 'Count by 2s',
    hintVi: 'Đếm theo bội số của 2',
    explanationEn: 'The pattern adds 2 each time. 8 + 2 = 10',
    explanationVi: 'Quy luật là cộng thêm 2. 8 + 2 = 10',
    xpReward: 10,
  },
  {
    unit: 3,
    exercise: '3.2',
    questionNum: 1,
    questionEn: 'What comes next: 10, 20, 30, 40, ?',
    questionVi: 'Số tiếp theo là gì: 10, 20, 30, 40, ?',
    answerEn: '50',
    answerVi: '50',
    type: 'pattern',
    difficulty: 1,
    hintEn: 'Count by 10s',
    hintVi: 'Đếm theo bội số của 10',
    explanationEn: 'The pattern adds 10 each time. 40 + 10 = 50',
    explanationVi: 'Quy luật là cộng thêm 10. 40 + 10 = 50',
    xpReward: 10,
  },
  // Unit 4 - Comparing numbers
  {
    unit: 4,
    exercise: '4.1',
    questionNum: 1,
    questionEn: 'Which is greater: 45 or 54?',
    questionVi: 'Số nào lớn hơn: 45 hay 54?',
    answerEn: '54',
    answerVi: '54',
    type: 'comparison',
    difficulty: 1,
    hintEn: 'Compare the tens digit first',
    hintVi: 'So sánh chữ số hàng chục trước',
    explanationEn: '54 > 45 because 5 tens > 4 tens',
    explanationVi: '54 > 45 vì 5 chục > 4 chục',
    xpReward: 10,
  },
  {
    unit: 4,
    exercise: '4.1',
    questionNum: 2,
    questionEn: 'Which is smaller: 67 or 76?',
    questionVi: 'Số nào nhỏ hơn: 67 hay 76?',
    answerEn: '67',
    answerVi: '67',
    type: 'comparison',
    difficulty: 1,
    hintEn: 'Compare the tens digit first',
    hintVi: 'So sánh chữ số hàng chục trước',
    explanationEn: '67 < 76 because 6 tens < 7 tens',
    explanationVi: '67 < 76 vì 6 chục < 7 chục',
    xpReward: 10,
  },
  // Unit 5 - Word problems
  {
    unit: 5,
    exercise: '5.1',
    questionNum: 1,
    questionEn: 'Tom has 25 apples. He buys 18 more. How many apples does he have now?',
    questionVi: 'Tom có 25 quả táo. Anh ấy mua thêm 18 quả. Hỏi Tom có bao nhiêu quả táo?',
    answerEn: '43',
    answerVi: '43',
    type: 'word_problem',
    difficulty: 2,
    hintEn: 'Add the apples together: 25 + 18',
    hintVi: 'Cộng số táo lại: 25 + 18',
    explanationEn: '25 + 18 = 43 apples',
    explanationVi: '25 + 18 = 43 quả táo',
    xpReward: 15,
  },
  {
    unit: 5,
    exercise: '5.1',
    questionNum: 2,
    questionEn: 'Sara has 52 stickers. She gives away 27. How many stickers does she have left?',
    questionVi: 'Sara có 52 nhãn dán. Cô ấy cho đi 27 cái. Hỏi Sara còn bao nhiêu nhãn dán?',
    answerEn: '25',
    answerVi: '25',
    type: 'word_problem',
    difficulty: 2,
    hintEn: 'Subtract: 52 - 27',
    hintVi: 'Trừ: 52 - 27',
    explanationEn: '52 - 27 = 25 stickers',
    explanationVi: '52 - 27 = 25 nhãn dán',
    xpReward: 15,
  },
  // More challenging problems
  {
    unit: 6,
    exercise: '6.1',
    questionNum: 1,
    questionEn: 'What is 48 + 36?',
    questionVi: '48 + 36 = ?',
    answerEn: '84',
    answerVi: '84',
    type: 'calculation',
    difficulty: 2,
    hintEn: '8 + 6 = 14, write 4 and carry 1',
    hintVi: '8 + 6 = 14, viết 4 nhớ 1',
    explanationEn: '48 + 36 = 84',
    explanationVi: '48 + 36 = 84',
    xpReward: 12,
  },
  {
    unit: 6,
    exercise: '6.1',
    questionNum: 2,
    questionEn: 'What is 63 - 28?',
    questionVi: '63 - 28 = ?',
    answerEn: '35',
    answerVi: '35',
    type: 'calculation',
    difficulty: 2,
    hintEn: 'Borrow from tens: 13 - 8 = 5',
    hintVi: 'Mượn từ hàng chục: 13 - 8 = 5',
    explanationEn: '63 - 28 = 35',
    explanationVi: '63 - 28 = 35',
    xpReward: 12,
  },
  {
    unit: 6,
    exercise: '6.2',
    questionNum: 1,
    questionEn: 'What comes next: 3, 6, 9, 12, ?',
    questionVi: 'Số tiếp theo là gì: 3, 6, 9, 12, ?',
    answerEn: '15',
    answerVi: '15',
    type: 'pattern',
    difficulty: 1,
    hintEn: 'Count by 3s',
    hintVi: 'Đếm theo bội số của 3',
    explanationEn: 'The pattern adds 3 each time. 12 + 3 = 15',
    explanationVi: 'Quy luật là cộng thêm 3. 12 + 3 = 15',
    xpReward: 10,
  },
  // Challenge problems
  {
    unit: 7,
    exercise: '7.1',
    questionNum: 1,
    questionEn: 'There are 34 birds in a tree. 19 fly away, then 12 more come. How many birds are there now?',
    questionVi: 'Có 34 con chim trên cây. 19 con bay đi, rồi 12 con khác đến. Hỏi bây giờ có bao nhiêu con chim?',
    answerEn: '27',
    answerVi: '27',
    type: 'word_problem',
    difficulty: 3,
    hintEn: 'First subtract, then add: (34 - 19) + 12',
    hintVi: 'Trừ trước, rồi cộng: (34 - 19) + 12',
    explanationEn: '34 - 19 = 15, then 15 + 12 = 27 birds',
    explanationVi: '34 - 19 = 15, sau đó 15 + 12 = 27 con chim',
    xpReward: 20,
  },
  {
    unit: 7,
    exercise: '7.1',
    questionNum: 2,
    questionEn: 'A shop has 78 toys. It sells 35 toys in the morning and 24 toys in the afternoon. How many toys are left?',
    questionVi: 'Một cửa hàng có 78 đồ chơi. Buổi sáng bán 35 cái, buổi chiều bán 24 cái. Hỏi còn lại bao nhiêu đồ chơi?',
    answerEn: '19',
    answerVi: '19',
    type: 'word_problem',
    difficulty: 3,
    hintEn: 'Subtract both amounts: 78 - 35 - 24',
    hintVi: 'Trừ cả hai số: 78 - 35 - 24',
    explanationEn: '78 - 35 = 43, then 43 - 24 = 19 toys',
    explanationVi: '78 - 35 = 43, sau đó 43 - 24 = 19 đồ chơi',
    xpReward: 20,
  },
  // Additional variety questions
  {
    unit: 3,
    exercise: '3.3',
    questionNum: 1,
    questionEn: 'Count by 5s: 25, 30, 35, ?, 45',
    questionVi: 'Đếm theo 5: 25, 30, 35, ?, 45',
    answerEn: '40',
    answerVi: '40',
    type: 'pattern',
    difficulty: 1,
    hintEn: 'What number comes between 35 and 45 when counting by 5s?',
    hintVi: 'Số nào nằm giữa 35 và 45 khi đếm theo 5?',
    explanationEn: '35 + 5 = 40',
    explanationVi: '35 + 5 = 40',
    xpReward: 10,
  },
  {
    unit: 4,
    exercise: '4.2',
    questionNum: 1,
    questionEn: 'Put in order from smallest to largest: 45, 32, 67. What is the middle number?',
    questionVi: 'Sắp xếp từ nhỏ đến lớn: 45, 32, 67. Số ở giữa là gì?',
    answerEn: '45',
    answerVi: '45',
    type: 'comparison',
    difficulty: 2,
    hintEn: 'First order them: 32, ?, 67',
    hintVi: 'Sắp xếp trước: 32, ?, 67',
    explanationEn: 'Order: 32, 45, 67. The middle number is 45.',
    explanationVi: 'Thứ tự: 32, 45, 67. Số ở giữa là 45.',
    xpReward: 12,
  },
  {
    unit: 2,
    exercise: '2.3',
    questionNum: 1,
    questionEn: 'What is 50 - 26?',
    questionVi: '50 - 26 = ?',
    answerEn: '24',
    answerVi: '24',
    type: 'calculation',
    difficulty: 2,
    hintEn: 'Borrow from 5 tens to make 10 ones',
    hintVi: 'Mượn từ 5 chục để có 10 đơn vị',
    explanationEn: '50 - 26 = 24',
    explanationVi: '50 - 26 = 24',
    xpReward: 12,
  },
  {
    unit: 1,
    exercise: '1.3',
    questionNum: 1,
    questionEn: 'What is 99 - 50?',
    questionVi: '99 - 50 = ?',
    answerEn: '49',
    answerVi: '49',
    type: 'calculation',
    difficulty: 1,
    hintEn: 'Subtract the tens: 90 - 50 = 40, keep the 9 ones',
    hintVi: 'Trừ hàng chục: 90 - 50 = 40, giữ 9 đơn vị',
    explanationEn: '99 - 50 = 49',
    explanationVi: '99 - 50 = 49',
    xpReward: 10,
  },
  {
    unit: 5,
    exercise: '5.2',
    questionNum: 1,
    questionEn: 'Mom baked 36 cookies. The children ate 14 cookies. How many cookies are left?',
    questionVi: 'Mẹ nướng 36 cái bánh quy. Các con ăn hết 14 cái. Hỏi còn lại bao nhiêu cái?',
    answerEn: '22',
    answerVi: '22',
    type: 'word_problem',
    difficulty: 2,
    hintEn: '36 - 14 = ?',
    hintVi: '36 - 14 = ?',
    explanationEn: '36 - 14 = 22 cookies left',
    explanationVi: '36 - 14 = 22 cái bánh quy còn lại',
    xpReward: 15,
  },
  {
    unit: 6,
    exercise: '6.3',
    questionNum: 1,
    questionEn: 'What is 29 + 29?',
    questionVi: '29 + 29 = ?',
    answerEn: '58',
    answerVi: '58',
    type: 'calculation',
    difficulty: 2,
    hintEn: 'Double 29: Think of it as 30 + 30 - 2',
    hintVi: 'Nhân đôi 29: Nghĩ như 30 + 30 - 2',
    explanationEn: '29 + 29 = 58',
    explanationVi: '29 + 29 = 58',
    xpReward: 12,
  },
  {
    unit: 7,
    exercise: '7.2',
    questionNum: 1,
    questionEn: 'I think of a number. I add 15 and get 42. What is my number?',
    questionVi: 'Em nghĩ một số. Em cộng thêm 15 và được 42. Số đó là bao nhiêu?',
    answerEn: '27',
    answerVi: '27',
    type: 'word_problem',
    difficulty: 3,
    hintEn: 'Work backwards: 42 - 15 = ?',
    hintVi: 'Làm ngược lại: 42 - 15 = ?',
    explanationEn: '42 - 15 = 27. Check: 27 + 15 = 42 ✓',
    explanationVi: '42 - 15 = 27. Kiểm tra: 27 + 15 = 42 ✓',
    xpReward: 20,
  },
  {
    unit: 7,
    exercise: '7.2',
    questionNum: 2,
    questionEn: 'I think of a number. I subtract 18 and get 25. What is my number?',
    questionVi: 'Em nghĩ một số. Em trừ đi 18 và được 25. Số đó là bao nhiêu?',
    answerEn: '43',
    answerVi: '43',
    type: 'word_problem',
    difficulty: 3,
    hintEn: 'Work backwards: 25 + 18 = ?',
    hintVi: 'Làm ngược lại: 25 + 18 = ?',
    explanationEn: '25 + 18 = 43. Check: 43 - 18 = 25 ✓',
    explanationVi: '25 + 18 = 43. Kiểm tra: 43 - 18 = 25 ✓',
    xpReward: 20,
  },
  {
    unit: 3,
    exercise: '3.4',
    questionNum: 1,
    questionEn: 'What comes next: 100, 90, 80, 70, ?',
    questionVi: 'Số tiếp theo là gì: 100, 90, 80, 70, ?',
    answerEn: '60',
    answerVi: '60',
    type: 'pattern',
    difficulty: 1,
    hintEn: 'Count backwards by 10',
    hintVi: 'Đếm ngược theo 10',
    explanationEn: 'The pattern subtracts 10 each time. 70 - 10 = 60',
    explanationVi: 'Quy luật là trừ đi 10. 70 - 10 = 60',
    xpReward: 10,
  },
]

async function main() {
  console.log('Seeding database...')

  // Create badges
  for (const badge of badges) {
    await prisma.badge.upsert({
      where: { name: badge.name },
      update: badge,
      create: badge,
    })
  }
  console.log(`✓ Seeded ${badges.length} badges`)

  // Create local questions
  for (const question of localQuestions) {
    await prisma.localQuestion.create({
      data: {
        unit: question.unit,
        exercise: question.exercise,
        questionNum: question.questionNum,
        questionEn: question.questionEn,
        questionVi: question.questionVi,
        answerEn: question.answerEn,
        answerVi: question.answerVi,
        type: question.type,
        difficulty: question.difficulty,
        hasImage: false,
        hintEn: question.hintEn,
        hintVi: question.hintVi,
        explanationEn: question.explanationEn,
        explanationVi: question.explanationVi,
        xpReward: question.xpReward,
      },
    })
  }
  console.log(`✓ Seeded ${localQuestions.length} local questions`)

  // Create a demo parent account
  const parent = await prisma.user.upsert({
    where: { username: 'parent' },
    update: {},
    create: {
      username: 'parent',
      password: 'parent123',
      name: 'Demo Parent',
      role: 'parent',
    },
  })

  // Create a demo child account
  await prisma.user.upsert({
    where: { username: 'demo' },
    update: {},
    create: {
      username: 'demo',
      password: 'demo123',
      name: 'Demo Kid',
      role: 'child',
      parentId: parent.id,
    },
  })
  console.log('✓ Seeded demo accounts')

  console.log('Database seeded successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
